### ISSUE TITLE
For AlexNet 

### ISSUE THREAD

**Issue by w-WYmm** [ShenZheng2000/MATH_32_HW1#1]
I am confuse that varaible num_classes in AlexNet is 10, but in the paper it is 1000 classes. I wonder whether there is something wrong:D.
`class AlexNet(nn.Module):
    def __init__(self, num_classes=10):`

**Comment by w-WYmm** [comment]
Also, when I run alexnet code part, I find it loaded lenet dataset,which is 1 * 28 * 28. May be we should write a new code part for alexnet.
`RuntimeError: Given groups=1, weight of size [96, 3, 11, 11], expected input[64, 1, 28, 28] to have 3 channels, but got 1 channels instead`

**Comment by w-WYmm** [comment]
I mean Optional part. We just write the code part or we should run the dataset by ourselves, and finally visualize it ?

**Comment by ShenZheng2000** [comment]
(1) Input Size: The MNIST classification is based on grayscale images. In the first convolution layer of AlexNet, you need to convert the input from a 1-channel representation (instead of the usual 3-channel RGB images) to 32-channel feature maps.

(2) Output Size: The original AlexNet is designed to classify into 1000 classes (some variants use 1024 classes). Since the MNIST dataset has only 10 classes representing numbers, you need to add a linear (fully connected) layer at the end to transform the 1000 (or 1024) classes into 10 classes.

(3) You'll need to write the code and run the dataset on your own. If you don't have a GPU or a powerful CPU, training AlexNet can be time-consuming. In case you're short on time, you can train with fewer epochs, such as 3 or 5, instead of the usual 10 epochs.

**Comment by w-WYmm** [comment]
Thanks! I solved it.
